//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPMDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatTourChiTiet
    {
        public int BookingDetailID { get; set; }
        public int BookingID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int TravelerCount { get; set; }
        public System.DateTime CreateAt { get; set; }
    
        public virtual DatTour DatTour { get; set; }
    }
}
