//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPMDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatTour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatTour()
        {
            this.DatTourChiTiets = new HashSet<DatTourChiTiet>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int BookingID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> ThanhToan { get; set; }
        public string MaThanhToan { get; set; }
        public Nullable<int> ContributorID { get; set; }
    
        public virtual Contributor Contributor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatTourChiTiet> DatTourChiTiets { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TourDuLich TourDuLich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
