//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPMDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourDuLich
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourDuLich()
        {
            this.DatTours = new HashSet<DatTour>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> TripStart { get; set; }
        public Nullable<System.DateTime> TripEnd { get; set; }
        public string LichTrinh { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<int> SoNguoiToiDa { get; set; }
        public string PhuongTien { get; set; }
        public Nullable<decimal> GiaTour { get; set; }
        public string BaiViet { get; set; }
        public Nullable<int> idTinh { get; set; }
        public Nullable<int> idLoaiTour { get; set; }
        public Nullable<int> idMucGia { get; set; }
        public int ContributorID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Contributor Contributor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatTour> DatTours { get; set; }
        public virtual LoaiTour LoaiTour { get; set; }
        public virtual MucGia MucGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual TinhThanh TinhThanh { get; set; }
    }
}
